apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-stateful
  namespace: fitness-ns
spec:
  replicas: {{ .Values.backend.replicaCount }}
  minReadySeconds: {{ .Values.backend.minReadySeconds }}
  selector:
    matchLabels:
      app: mysql
  # updateStrategy:
  #   type: RollingUpdate
    # rollingUpdate:
    #   maxUnavailable: 1
    #   maxSurge: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: {{ .Values.backend.terminationGracePeriodSeconds }}
      containers:
        - name: mysql-cont
          image: mysql
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.backend.requests.cpu }}
              memory: {{ .Values.backend.requests.memory }}
            limits:
              cpu: {{ .Values.backend.limits.cpu }}
              memory: {{ .Values.backend.limits.cpu }}
          envFrom:
            - configMapRef:
                name: university-config
            - secretRef:
                name: university-secret
          #env:
            # - name: MYSQL_ROOT_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: university-secret
            #       key: MYSQL_ROOT_PASSWORD
            # - name: DB_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: university-secret
            #       key: DB_USER
            # - name: DB_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: university-secret
            #       key:  DB_PASSWORD
            # - name: DB_HOST
            #   valueFrom:
            #     configMapKeyRef:
            #       name: university-config
            #       key: DB_HOST
            # - name: DB_PORT
            #   valueFrom:
            #     configMapKeyRef:
            #       name: university-config
            #       key: DB_PORT
          volumeMounts:
            - name: {{ .Values.backend.vct.name }}
              mountPath: /var/lib/mysql
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-init
          configMap:
            name: mysql-config
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.backend.vct.name }}
      spec:
        accessModes: {{ .Values.backend.vct.accessModes }}
        storageClassName: {{ .Values.backend.storageClass.name }}
        resources:
          requests:
            storage: {{ .Values.backend.vct.storage }}
          
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: fitness-ns
spec:
  selector:
    app: mysql
  ports:
    - port: {{ .Values.backend.port}}
      targetPort: {{ .Values.backend.containerPort }}
  clusterIP: None

