apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-stateful
  namespace: fitness-ns
spec:
  serviceName: mysql-service
  replicas: {{ .Values.backend.replicaCount }}
  minReadySeconds: {{ .Values.backend.minReadySeconds }}
  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: {{ .Values.backend.terminationGracePeriodSeconds }}

      containers:
        - name: mysql-cont
          image: mysql

          command:
            - bash
            - "-c"
            - |
              if [[ $(hostname) == "mysql-stateful-0" ]]; then
                echo "I am PRIMARY"
                cp /etc/mysql/repl/primary.cnf /etc/mysql/conf.d/
              else
                echo "I am REPLICA"
                cp /etc/mysql/repl/replica.cnf /etc/mysql/conf.d/
              fi
              docker-entrypoint.sh mysqld

          ports:
            - containerPort: {{ .Values.backend.containerPort }}

          resources:
            requests:
              cpu: {{ .Values.backend.requests.cpu }}
              memory: {{ .Values.backend.requests.memory }}
            limits:
              cpu: {{ .Values.backend.limits.cpu }}
              memory: {{ .Values.backend.limits.memory }}

          envFrom:
            - configMapRef:
                name: university-config
            - secretRef:
                name: university-secret

          volumeMounts:
            - name: {{ .Values.backend.vct.name }}
              mountPath: /var/lib/mysql

            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d

            # 🔥 NEW (replication config mount)
            - name: mysql-repl-config
              mountPath: /etc/mysql/repl

      volumes:
        - name: mysql-init
          configMap:
            name: mysql-config

        # 🔥 NEW volume
        - name: mysql-repl-config
          configMap:
            name: mysql-replication-config

  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.backend.vct.name }}
      spec:
        accessModes: ["ReadWriteOnce"]   # ✅ FIXED (important)
        storageClassName: {{ .Values.storageClass.name }}
        resources:
          requests:
            storage: {{ .Values.backend.vct.storage }}

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: fitness-ns
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.containerPort }}
