apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: fitness-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-cont
          image: mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: university-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: university-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: university-secret
                  key:  DB_PASSWORD
            # - name: DB_HOST
            #   valueFrom:
            #     configMapKeyRef:
            #       name: university-config
            #       key: DB_HOST
            # - name: DB_PORT
            #   valueFrom:
            #     configMapKeyRef:
            #       name: university-config
            #       key: DB_PORT
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: university-pvc
        - name: mysql-init
          configMap:
            name: mysql-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: fitness-ns
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP

