apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: university-pvc
  namespace: fitness-ns
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: university-storage